### ISSUE TITLE
Mod0 Website Usability

### ISSUE THREAD

**Issue by memcmahon** [turingschool/launch-curriculum#18]

**Comment by memcmahon** [comment]
@rtillies and @zoefarrell - I think we are there, but would love another set of eyes just to double check :) 

Updated site is live at launch.turing.edu

All links and images should be working.

You can also show instructor notes by running `showInstructorNotes()` in the console.

**Comment by rtillies** [comment]
@memcmahon 

Technical Day 1
- Under Computer Observations, should the second Variables link be Display Variables instead?

Mod 0 Syllabus:
- Zoom links (retro discussion)
- Reasonable Accommodation Request Form is a FE form (mentions Ellen Mary and Will)

Google Suite
- Under Google Slides, the link for this Practice Deck can be updated to end with `/copy` to force students to make a copy

**Comment by memcmahon** [comment]
Thanks!! The Technical Day has been updated - I'll update the Mod0 Syllabus pending our retro discussion.

I couldn't get the /copy to work - could you send me what the url should be?  I tried adding /copy to the end, and replacing share with copy, but it is still just opening the view only version (even when I tried in incognito mode)
