### ISSUE TITLE
Split M2W1 Labs into Prep and Practice

### ISSUE THREAD

**Issue by memcmahon** [turingschool/launch-curriculum#57]

**Comment by rtillies** [comment]
Looks great, like the Pre-work labels for Intro to Databases, CRUD, and TDD.
Quick question @memcmahon , this step is separate from actually populating these files, correct?

**Comment by memcmahon** [comment]
That's a good question.... What I did was split the previously completed lab (Intro to Database) into the lap and prep for SQL CRUD.  Then I completed the Lab for SQL CRUD.  I was imagining that moving forward, we could include the preparation as part of the lesson creation ?

**Comment by memcmahon** [comment]
Now that I'm looking at it again, I'm going to group the prep into weeks, similar to lessons and labs.
