### ISSUE TITLE
Retro Template

### ISSUE THREAD

**Issue by memcmahon** [turingschool/launch-curriculum#75]
Here is the current retro draft, I also added wins and appreciations to the end: https://docs.google.com/presentation/d/1NFNERIe63x33fnBaJ4snrDWnSLu48DtFd4oIezvqg3E/edit?usp=sharing

Here is the end of week survey draft: https://docs.google.com/forms/d/e/1FAIpQLSc4kvztY03870VodHNRHzF0CSRWx56hRjZix2Ug3Bj8aEyPzQ/viewform?usp=sharing

Here is the mod 0 survey draft: https://docs.google.com/forms/d/e/1FAIpQLScCuBU_N_F1GdOuS5Yw8SWD7o7PRTr5byVaWCrx0HOaL0DUsg/viewform?usp=sharing

**Comment by memcmahon** [comment]
Including an end of week survey

**Comment by zoefarrell** [comment]
Mod 1 surveys FE: https://drive.google.com/drive/u/1/folders/1OyuJXnlwh-iRiecVrmVBkjJMJeKJS5Wz
Mod 1 surveys BE: https://drive.google.com/drive/u/1/folders/1UX8M0r_9o6fJJHiu1WpRGLw_BYtKCRF_

**Comment by zoefarrell** [comment]
FE Mod 1 Week 1 Retro: https://docs.google.com/presentation/d/1a6a1SVLPGJrqIOSsvwdaYiAaOwL1IbJnV_K8KhLptpQ/edit#slide=id.g9232df1de7_0_16
BE Mod 1 Week 1 Retro: https://docs.google.com/presentation/d/1RG1hLTduhLJqG_7rhdz67iM9cjctGImeK3awujNTLC4/edit#slide=id.g1c033f9cd5_0_107
With jam board like this: https://jamboard.google.com/d/1r3IooPjbfCC3OZsFVu3_2RFWjAQnicPiLNaqssIoxHk/viewer?f=0

**Comment by memcmahon** [comment]
These look good!  I think the retro slides will be easy to duplicate/update per week.  We could duplicate the survey for each week, or we could remove references to the week, and use the same survey for each week - would cut down on admin tasks :)

**Comment by zoefarrell** [comment]
Ooo an interesting idea to just use the same survey every time! I like that, less to keep track of the better especially for round 1 of Launch.
